logging:
  level:
    org.springframework.security: DEBUG
spring:
    datasource:
        driverClassName: org.h2.Driver
        password: ''
        url: jdbc:h2:~/testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: sa
    h2:
        console:
            enabled: true
            path: /console
    jpa:
        database: H2
        database-platform: org.hibernate.dialect.H2Dialect
        format-sql: true
        hibernate:
            ddl-auto: create-drop
        show-sql: true